export const products = [
  {
    id: "001",
    name: "Roberto Verino",
    description: "Conjunto de pijama de hombre jersey marino.",
    price: 90.0,
    discount: 10,
    stock: 30,
    img: [
      "./src/images/products/001_1.jpg",
      "./src/images/products/001_2.jpg",
      "./src/images/products/001_3.jpg",
    ],
    stars: 4,
  },
  {
    id: "002",
    name: "Dustin",
    description: "Bata de hombre polar.",
    price: 90.0,
    stock: 24,
    img: [
      "./src/images/products/002_1.webp",
      "./src/images/products/002_2.webp",
      "./src/images/products/002_3.webp",
    ],
    stars: 3,
  },
  {
    id: "003",
    name: "EASY WEAR",
    description: "Pijama licencia manga larga Marvel de hombre",
    price: 150,
    stock: 33,
    img: [
      "./src/images/products/003_1.webp",
      "./src/images/products/003_2.webp",
      "./src/images/products/003_3.webp",
    ],
    discount: 20,
    stars: 5,
  },
  {
    id: "004",
    name: "Sfera",
    description: "Pijama de mujer polar moonlight.",
    price: 120,
    stock: 28,
    img: ["./src/images/products/004_1.webp"],
    stars: 3,
  },
  {
    id: "005",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
];
