export const products = [
  {
    id: "001",
    name: "Roberto Verino",
    description: "Conjunto de pijama de hombre jersey marino.",
    price: 90.0,
    discount: 10,
    stock: 30,
    img: [
      "./src/images/products/001_1.jpg",
      "./src/images/products/001_2.jpg",
      "./src/images/products/001_3.jpg",
    ],
    stars: 4,
  },
  {
    id: "002",
    name: "Dustin",
    description: "Bata de hombre polar.",
    price: 90.0,
    stock: 24,
    img: [
      "./src/images/products/002_1.webp",
      "./src/images/products/002_2.webp",
      "./src/images/products/002_3.webp",
    ],
    stars: 3,
  },
  {
    id: "003",
    name: "EASY WEAR",
    description: "Pijama licencia manga larga Marvel de hombre",
    price: 150,
    stock: 33,
    img: [
      "./src/images/products/003_1.webp",
      "./src/images/products/003_2.webp",
      "./src/images/products/003_3.webp",
    ],
    discount: 20,
    stars: 5,
  },
  {
    id: "004",
    name: "Sfera",
    description: "Pijama de mujer polar moonlight.",
    price: 120,
    stock: 28,
    img: ["./src/images/products/004_1.webp"],
    stars: 3,
  },
  {
    id: "005",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "006",
    name: "ALAN PAINE",
    description: "Jersey de lana 100% de hombre con el cuello redondo.",
    price: 140,
    discount: 15,
    stock: 24,
    img: [
      "./src/images/products/006_1.webp",
      "./src/images/products/006_2.webp",
      "./src/images/products/006_3.webp",
      "./src/images/products/006_4.webp",
    ],
    stars: 3,
  },
  {
    id: "007",
    name: "TOMMY HILFIGER",
    description:
      "Zapatillas de hombre en blanco bajas tipo casco de cuero con banda corporativa.",
    price: 350,
    stock: 0,
    img: [
      "./src/images/products/007_1.webp",
      "./src/images/products/007_2.webp",
      "./src/images/products/007_3.webp",
    ],
    stars: 4,
  },
  {
    id: "008",
    name: "LACOSTE",
    description: "Zapatillas de hombre en marr[on Powercut vulcanizado",
    price: 420,
    stock: 15,
    img: [
      "./src/images/products/008_1.webp",
      "./src/images/products/008_2.webp",
      "./src/images/products/008_3.webp",
    ],
    stars: 5,
    discount: 15,
  },
  {
    id: "009",
    name: "HAWKERS",
    description: "Lentes de sol unisex redondos en azul marino.",
    price: 130,
    stock: 120,
    img: [
      "./src/images/products/009_1.webp",
      "./src/images/products/009_2.webp",
      "./src/images/products/009_3.webp",
    ],
    stars: 3,
  },
  {
    id: "010",
    name: "LAUREN RALPH LAUREN",
    description: "Pantalón de mujer Lauren Ralph Lauren negro.",
    price: 130,
    stock: 12,
    img: [
      "./src/images/products/010_1.webp",
      "./src/images/products/010_2.webp",
      "./src/images/products/010_3.webp",
      "./src/images/products/010_4.webp",
    ],
    stars: 4,
    discount: 30,
  },
  {
    id: "011",
    name: "LLOYD'S",
    description: "Pantalón de mujer con bolsillos.",
    price: 125,
    stock: 27,
    img: ["./src/images/products/011_1.webp"],
    stars: 3,
  },
  {
    id: "012",
    name: "SFERA",
    description: "Vestido de terciopelo strass de niña.",
    price: 80,
    stock: 34,
    img: ["./src/images/products/012_1.webp"],
    stars: 4,
  },
  {
    id: "013",
    name: "DESIGUAL",
    description: "Vestido de niña con corazón.",
    price: 180,
    stock: 33,
    img: [
      "./src/images/products/013_1.webp",
      "./src/images/products/013_2.webp",
      "./src/images/products/013_3.webp",
    ],
    stars: 4,
    discount: 30,
  },
  {
    id: "014",
    name: "TOMMY HILFIGER",
    description: "Reloj de hombre San Diego 1792039 de nailon negro y gris.",
    price: 650,
    stock: 5,
    img: [
      "./src/images/products/014_1.webp",
      "./src/images/products/014_2.webp",
      "./src/images/products/014_3.webp",
    ],
    discount: 10,
    stars: 4,
  },
  {
    id: "015",
    name: "CALVIN KLEIN",
    description: "Billetera de cuero negro con monedero.",
    price: 430,
    stock: 3,
    img: [
      "./src/images/products/015_1.webp",
      "./src/images/products/015_2.webp",
      "./src/images/products/015_3.webp",
    ],
    stars: 4,
  },
  {
    id: "016",
    name: "GUESS",
    description: "Billetera negra con monedero.",
    price: 320,
    stock: 0,
    img: [
      "./src/images/products/016_1.webp",
      "./src/images/products/016_2.webp",
      "./src/images/products/016_3.webp",
    ],
    stars: 4,
  },
  {
    id: "017",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "018",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "019",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "020",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "021",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "022",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "023",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
  {
    id: "024",
    name: "TINTORETTO",
    description: "Casaca de mujer oversize doble faz.",
    price: 250,
    stock: 0,
    img: [
      "./src/images/products/005_1.webp",
      "./src/images/products/005_2.webp",
      "./src/images/products/005_3.webp",
      "./src/images/products/005_4.webp",
    ],
    stars: 4,
  },
];
